# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b14675b8-323a-41d0-abaf-44a794ceb171'
  imageRepository: 'aznamingtool'
  containerRegistry: 'collectorcontainerregistryprod.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/govern/AzureGovernanceVisualizer/.devcontainer/Dockerfile'
  buildContext: '$(Build.SourcesDirectory)/ready/AzNamingTool'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        docker build -t $(containerRegistry)/$(imageRepository):$(tag) -f $(dockerfilePath) $(buildContext)
      displayName: 'Docker Build'
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)